version: '3.8'

services:
  # Discord Bot Backend (Flask 템플릿 포함)
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_TOKEN=${USER_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./web:/app/web
      - ./assets:/app/assets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
